# Stochastic Gradient Descent Implementation

1. SGD Classifier

+ Stochastic Gradient Descent (SGD) classifier basically implements a plain SGD learning routine supporting various loss functions and penalties for classification. 

In [1]:
import numpy as np
from sklearn import linear_model
X = np.array([[-1, -1], [-2, -1], [1, 1], [2, 1]])
Y = np.array([1, 1, 2, 2])
SGDClf = linear_model.SGDClassifier(max_iter = 1000, tol=1e-3,penalty = "elasticnet")
SGDClf.fit(X, Y)

SGDClassifier(penalty='elasticnet')

The model can predict new values

In [2]:
SGDClf.predict([[2.,2.]])

array([2])

We can get the weight vector by following:

In [3]:
SGDClf.coef_

array([[9.77200712, 9.77200712]])

the value of intercept

In [4]:
SGDClf.intercept_

array([-10.])

The signed distance to the hyperplane

In [5]:
SGDClf.decision_function([[2., 2.]])

array([29.08802849])

2. SGD Regressor

+ Stochastic Gradient Descent (SGD) regressor basically implements a plain SGD learning routine supporting various loss functions and penalties to fit linear regression models.

In [6]:
import numpy as np
from sklearn import linear_model
n_samples, n_features = 10, 5
rng = np.random.RandomState(0)
y = rng.randn(n_samples)
X = rng.randn(n_samples, n_features)
SGDReg =linear_model.SGDRegressor(
   max_iter = 1000,penalty = "elasticnet",loss = 'huber',tol = 1e-3, average = True
)
SGDReg.fit(X, y)

SGDRegressor(average=True, loss='huber', penalty='elasticnet')

the weight vector 

In [7]:
SGDReg.coef_

array([-0.00403343,  0.00393679, -0.00390104,  0.00633158,  0.00390666])

the value of intercept 

In [10]:
SGDReg.intercept_

array([0.00655381])

the number of weight updates during training phase

In [11]:
SGDReg.t_

61.0